### PR TITLE
Update lnurl.py

### PR DESCRIPTION
**Pull request by supiiik**
Prevent double spend by checking, if payload is already in DB. If yes, then it's not adding new line into the DB with same payload.

In case of failed transaction is returned payhash value to "payment_hash" so user can try the QR code again with different wallet.

### CODE REVIEW

**Review by dni — APPROVED** [review]

**Comment by arcbtc** [comment]
You cant currently double spend

**Comment by supiiik** [comment]
> You cant currently double spend, so it does not require a fix

#15 check this issue, the fix was required

**Review by Merysol — APPROVED** [review]

**Comment by dni** [comment]
can you resolve the conflicts?

**Comment by arcbtc** [comment]
Fixed this issue another way

**Pull request closed without merging**
